name: Build npm package

on:
  push:
    branches:
      - master
      - main
    paths:
      - package.json
      - .npmrc
      - .github/workflows/build-npm.yml

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    env:
      PKGNAME: nestjs-monitor

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jan-tee'
      - name: Install dependencies
        run: |
          npm install
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: Build
        run: |
          npm run build
      - name: Publishing to local registry
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}